/// Minimal Apache Thrift binary protocol + framed-transport client for
/// Prism HSM's `TokenApi`.
///
/// Scope is **deliberately small**: only the wire features the Prism
/// `TokenApi` service actually uses, hand-rolled so this repo doesn't
/// have to pull a full Thrift toolchain.
///
/// Wire format reference (Thrift 0.12, what Prism is compiled against):
///   - Framed transport: each message is prefixed with a big-endian
///     i32 frame length. Server expects the same on the way back.
///   - Binary protocol, strict header:
///       i32 (VERSION_1=0x80010000 | msgType in low byte)
///       string name
///       i32 seqId
///     followed by the args struct, then the protocol/transport
///     equivalent of writeMessageEnd + flush.
///   - Struct: sequence of (field-type i8, field-id i16, value)
///     entries, terminated by STOP=0x00.
///   - String/binary: i32 length + raw bytes (no NUL term).
///   - List: elem-type i8, size i32, then elements.
///
/// The reference Java implementation is at
/// `c:\www\java\tokens-service\src\main\java\ke\co\nectar\hsm\prism\`
/// (auto-generated by `org.apache.thrift:thrift-compiler:0.12.0`).
library;

import 'dart:convert';
import 'dart:typed_data';

// ---- Wire constants --------------------------------------------------

/// Thrift binary-protocol field types (`TType.*`).
class TType {
  TType._();
  static const int stop = 0;
  static const int voidType = 1;
  static const int bool_ = 2;
  static const int byte = 3;
  static const int double_ = 4;
  static const int i16 = 6;
  static const int i32 = 8;
  static const int i64 = 10;
  static const int string = 11;
  static const int struct = 12;
  static const int map = 13;
  static const int set = 14;
  static const int list = 15;
}

/// Thrift message types (`TMessageType.*`).
class TMessageType {
  TMessageType._();
  static const int call = 1;
  static const int reply = 2;
  static const int exception = 3;
  static const int oneway = 4;
}

/// Strict binary-protocol version flag (`VERSION_1 = 0x80010000`).
const int _versionMask = 0xFFFF0000;
const int _version1 = 0x80010000;

/// Decoded message header.
class TMessage {
  final String name;
  final int type;
  final int seqId;
  const TMessage(this.name, this.type, this.seqId);
}

/// Thrown when the server returns a `TApplicationException`-shaped
/// reply (i.e. an unknown method, protocol error, etc.).
class TApplicationException implements Exception {
  static const int unknown = 0;
  static const int unknownMethod = 1;
  static const int invalidMessageType = 2;
  static const int wrongMethodName = 3;
  static const int badSequenceId = 4;
  static const int missingResult = 5;

  final int type;
  final String message;
  const TApplicationException(this.type, this.message);
  @override
  String toString() => 'TApplicationException(type=$type, message="$message")';
}

/// Thrown when the wire data violates the binary protocol or
/// framed-transport framing.
class TProtocolException implements Exception {
  final String message;
  const TProtocolException(this.message);
  @override
  String toString() => 'TProtocolException("$message")';
}

// ---- Codec ----------------------------------------------------------

/// Append-only big-endian byte buffer for outgoing frames.
class BinaryWriter {
  final BytesBuilder _b = BytesBuilder(copy: false);

  Uint8List takeBytes() => _b.takeBytes();

  void writeByte(int v) => _b.addByte(v & 0xFF);

  void writeBool(bool v) => _b.addByte(v ? 1 : 0);

  void writeI16(int v) {
    final bd = ByteData(2)..setInt16(0, v, Endian.big);
    _b.add(bd.buffer.asUint8List());
  }

  void writeI32(int v) {
    final bd = ByteData(4)..setInt32(0, v, Endian.big);
    _b.add(bd.buffer.asUint8List());
  }

  void writeI64(int v) {
    final bd = ByteData(8)..setInt64(0, v, Endian.big);
    _b.add(bd.buffer.asUint8List());
  }

  void writeDouble(double v) {
    final bd = ByteData(8)..setFloat64(0, v, Endian.big);
    _b.add(bd.buffer.asUint8List());
  }

  void writeBinary(List<int> bytes) {
    writeI32(bytes.length);
    _b.add(bytes);
  }

  void writeString(String s) => writeBinary(utf8.encode(s));

  void writeMessageBegin(TMessage m) {
    writeI32(_version1 | (m.type & 0xFF));
    writeString(m.name);
    writeI32(m.seqId);
  }

  void writeFieldBegin(int type, int fieldId) {
    writeByte(type);
    writeI16(fieldId);
  }

  void writeFieldStop() => writeByte(TType.stop);

  void writeListBegin(int elemType, int size) {
    writeByte(elemType);
    writeI32(size);
  }

  void writeMapBegin(int keyType, int valueType, int size) {
    writeByte(keyType);
    writeByte(valueType);
    writeI32(size);
  }
}

/// Random-access big-endian reader over a pre-buffered frame.
class BinaryReader {
  final Uint8List _bytes;
  final ByteData _view;
  int _pos = 0;

  BinaryReader(this._bytes) : _view = ByteData.sublistView(_bytes);

  int get offset => _pos;
  int get remaining => _bytes.length - _pos;

  void _need(int n) {
    if (_pos + n > _bytes.length) {
      throw TProtocolException(
        'short read: need $n bytes at $_pos but only $remaining left',
      );
    }
  }

  int readByte() {
    _need(1);
    return _bytes[_pos++];
  }

  bool readBool() => readByte() != 0;

  int readI16() {
    _need(2);
    final v = _view.getInt16(_pos, Endian.big);
    _pos += 2;
    return v;
  }

  int readI32() {
    _need(4);
    final v = _view.getInt32(_pos, Endian.big);
    _pos += 4;
    return v;
  }

  int readI64() {
    _need(8);
    final v = _view.getInt64(_pos, Endian.big);
    _pos += 8;
    return v;
  }

  double readDouble() {
    _need(8);
    final v = _view.getFloat64(_pos, Endian.big);
    _pos += 8;
    return v;
  }

  Uint8List readBinary() {
    final n = readI32();
    if (n < 0) throw TProtocolException('negative binary length: $n');
    _need(n);
    final out = Uint8List.sublistView(_bytes, _pos, _pos + n);
    _pos += n;
    return out;
  }

  String readString() => utf8.decode(readBinary());

  TMessage readMessageBegin() {
    final v = readI32();
    if ((v & _versionMask) != _version1) {
      throw TProtocolException(
        'bad version in message header: 0x${v.toRadixString(16)}',
      );
    }
    final type = v & 0xFF;
    final name = readString();
    final seqId = readI32();
    return TMessage(name, type, seqId);
  }

  /// `(type, fieldId)`. `type == TType.stop` marks end of struct;
  /// fieldId is then meaningless.
  (int, int) readFieldBegin() {
    final type = readByte();
    if (type == TType.stop) return (type, 0);
    final id = readI16();
    return (type, id);
  }

  /// `(elemType, size)` for both list and set.
  (int, int) readListBegin() {
    final t = readByte();
    final n = readI32();
    if (n < 0) throw TProtocolException('negative list size: $n');
    return (t, n);
  }

  /// `(keyType, valueType, size)`.
  (int, int, int) readMapBegin() {
    final kt = readByte();
    final vt = readByte();
    final n = readI32();
    if (n < 0) throw TProtocolException('negative map size: $n');
    return (kt, vt, n);
  }

  /// Read and discard a field of [type]. Used to ignore unknown
  /// fields without dropping the rest of the stream.
  void skip(int type) {
    switch (type) {
      case TType.bool_:
      case TType.byte:
        _need(1);
        _pos += 1;
        break;
      case TType.i16:
        _need(2);
        _pos += 2;
        break;
      case TType.i32:
        _need(4);
        _pos += 4;
        break;
      case TType.i64:
      case TType.double_:
        _need(8);
        _pos += 8;
        break;
      case TType.string:
        readBinary();
        break;
      case TType.struct:
        while (true) {
          final (t, _) = readFieldBegin();
          if (t == TType.stop) break;
          skip(t);
        }
        break;
      case TType.list:
      case TType.set:
        final (elemType, n) = readListBegin();
        for (var i = 0; i < n; i++) {
          skip(elemType);
        }
        break;
      case TType.map:
        _need(1);
        final kt = _bytes[_pos++];
        _need(1);
        final vt = _bytes[_pos++];
        final n = readI32();
        for (var i = 0; i < n; i++) {
          skip(kt);
          skip(vt);
        }
        break;
      default:
        throw TProtocolException('cannot skip unknown TType $type');
    }
  }
}
